deployments:
  jeeshop:
    name: jeeshop
    autoscaling:
      # -- Controls autoscaling
      enabled: true
      # -- Minimum number of replicas
      minReplicas: 1
      # -- Minimum number of replicas
      maxReplicas: 3
    # -- Number of replicas
    replicaCount: 1

    # -- Labels used on the deployment
    podLabels:
      handler: G-FinOps
      application: jeeshop
      environment: default
      team: FinOps
      owner: My_Organization

    # -- List of image pull secrets
    imagePullSecrets:
    podSecurityContext:

    containers:
      jeeshop:
        name: jeeshop

        livenessProbe:
          httpGet:
            path: /
            port: 8080

        readinessProbe:
          httpGet:
            path: /
            port: 8080

        resources:
          requests:
            memory: 180Mi
            cpu: 250m

          limits:
            memory: 256Mi
            cpu: 500m

        image:
          repository: jeeshop
          tag: 1.0.0
          pullPolicy:
        securityContext:

    nodeSelector:
    affinity:
    tolerations:

  postgres:
    name: postgres
    autoscaling:
      # -- Controls autoscaling
      enabled: true
      # -- Minimum number of replicas
      minReplicas: 1
      # -- Minimum number of replicas
      maxReplicas: 3
    # -- Number of replicas
    replicaCount: 1

    # -- Labels used on the deployment
    podLabels:
      handler: G-FinOps
      application: postgres
      environment: default
      team: FinOps
      owner: My_Organization

    # -- List of image pull secrets
    imagePullSecrets:
    podSecurityContext:

    containers:
      postgres:
        name: postgres

        livenessProbe:

        readinessProbe:
        resources:
          requests:
            memory: 128Mi
            cpu: 250m

          limits:
            memory: 256Mi
            cpu: 500m

        image:
          repository: postgres
          tag: latest
          pullPolicy:
        securityContext:

    nodeSelector:
    affinity:
    tolerations:

services:
  jeeshop:
    port: 8080
    type: ClusterIP

  postgres:
    port: 5432
    type: ClusterIP

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""

ingresses:
  jeeshop:
    # -- Enable ingress
    enabled: true
    # -- Ingress class name
    className: ""
    # -- Ingress annotations
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # -- Ingress jpsts
    hosts:
      - host: jeeshop.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  postgres:
    # -- Enable ingress
    enabled: true
    # -- Ingress class name
    className: ""
    # -- Ingress annotations
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # -- Ingress jpsts
    hosts:
      - host: postgres.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
