{{- if .Values.deployments.homepage.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: homepage-{{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "deployments.homepage.name" . }}
  minReplicas: {{ .Values.deployments.homepage.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.deployments.homepage.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.deployments.homepage.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.homepage.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.deployments.homepage.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployments.homepage.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
