
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deployments.homepage.name" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- include "deployments.homepage.labels" . | nindent 4 }}
spec:
  {{- if not .Values.deployments.homepage.autoscaling.enabled }}
  replicas: {{ .Values.deployments.homepage.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      {{- with .Values.deployments.homepage.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      {{- with .Values.deployments.homepage.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        {{- with .Values.deployments.homepage.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.deployments.homepage.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployments.homepage.podSecurityContext | nindent 8 }}
      
      containers:
        - name: {{.Values.deployments.homepage.containers.homepage.name}}        
          securityContext:
            {{- toYaml .Values.deployments.homepage.containers.homepage.securityContext | nindent 12 }}
          image: "{{ .Values.deployments.homepage.containers.homepage.image.repository }}:{{ .Values.deployments.homepage.containers.homepage.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployments.homepage.containers.homepage.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.services.homepage.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.deployments.homepage.containers.homepage.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.deployments.homepage.containers.homepage.readinessProbe | nindent 12 }}
          env:
          
          resources:
            {{- toYaml .Values.deployments.homepage.containers.homepage.resources | nindent 12 }}
          {{- with .Values.deployments.homepage.containers.homepage.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      
      {{- with .Values.deployments.homepage.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployments.homepage.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployments.homepage.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployments.homepage.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
