
apiVersion: v1
kind: Service
metadata:
  name: jeeshop-{{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.jeeshop.type }}
  ports:
    - port: {{ .Values.services.jeeshop.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
	{{- with .Values.deployments.jeeshop.podLabels }}
	{{- toYaml . | nindent 4 }}
	{{- end }}
