
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.postgres.type }}
  ports:
    - port: {{ .Values.services.postgres.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
	{{- with .Values.deployments.postgres.podLabels }}
	{{- toYaml . | nindent 4 }}
	{{- end }}
