deployments:
  wonky:
    name: wonky
    autoscaling:
      # -- Controls autoscaling
      enabled: true
      # -- Minimum number of replicas
      minReplicas: 1
      # -- Minimum number of replicas
      maxReplicas: 3
    # -- Number of replicas
    replicaCount: 1

    # -- Labels used on the deployment
    podLabels:
      handler: G-FinOps
      application: wonky
      environment: default
      team: FinOps
      owner: My_Organization

    # -- List of image pull secrets
    imagePullSecrets:
    podSecurityContext:

    containers:
      wonky:
        name: wonky

        livenessProbe:
          httpGet:
            path: /
            port: 8080

        readinessProbe:
          httpGet:
            path: /
            port: 8080

        resources:
          requests:
            memory: 160Mi
            cpu: 350m

          limits:
            memory: 256Mi
            cpu: 500m

        image:
          repository: wonky
          tag: 1.0.0
          pullPolicy:
        securityContext:
        volumeMounts:
          - name: configuration-files-volume
            mountPath: /etc/wonky/tenants.yaml
            subPath: tenants.yaml

    volumes:
      - name: configuration-files-volume
        configMap:
          name: configuration-files
          optional: false

    nodeSelector:
    affinity:
    tolerations:

services:
  wonky:
    port: 8080
    type: ClusterIP

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""

ingresses:
  wonky:
    # -- Enable ingress
    enabled: true
    # -- Ingress class name
    className: ""
    # -- Ingress annotations
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # -- Ingress jpsts
    hosts:
      - host: wonky.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
