deployments:
  homepage:
    name: homepage
    autoscaling:
      # -- Controls autoscaling
      enabled: true
      # -- Minimum number of replicas
      minReplicas: 1
      # -- Minimum number of replicas
      maxReplicas: 3
    # -- Number of replicas
    replicaCount: 1

    # -- Labels used on the deployment
    podLabels:
      handler: G-FinOps
      application: homepage
      environment: default
      team: FinOps
      owner: My_Organization

    # -- List of image pull secrets
    imagePullSecrets:
    podSecurityContext:

    containers:
      homepage:
        name: homepage

        livenessProbe:
          httpGet:
            path: /
            port: 3000

        readinessProbe:
          httpGet:
            path: /
            port: 3000

        resources:
          requests:
            memory: 128Mi
            cpu: 50m

          limits:
            memory: 256Mi
            cpu: 200m

        image:
          repository: homepage
          tag: 1.0.0
          pullPolicy:
        securityContext:
        volumeMounts:

    volumes:
      - name: configuration-files-volume
        configMap:
          name: configuration-files
          optional: false

    nodeSelector:
    affinity:
    tolerations:

services:
  homepage:
    port: 3000
    type: ClusterIP

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""

ingresses:
  homepage:
    # -- Enable ingress
    enabled: true
    # -- Ingress class name
    className: ""
    # -- Ingress annotations
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # -- Ingress jpsts
    hosts:
      - host: homepage.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
