apiVersion: v1
kind: ConfigMap
metadata:
  name: "configuration-files"
  labels: {{- include "chart.labels" . | nindent 4}}
data:
  tenants.yaml: |

    - !!wonky.service.SlackOrganization
      token: "xoxp-XXXXXXXXXX"
      wonkyDomain: "slack.myorganization.com"
